### ISSUE TITLE
Hexview: syncronize selection of bytes in hex culumns with the column in ASCII

### ISSUE THREAD

**Issue by msgpeek** [takeshixx/deen#27]
Feature suggestion:

Basically, what Wireshark does with selected protocol fields and within its hex view.

The selection should be synchronized from from the ASCII column to the hex columns and the other way around.
This is handy when analyzing binary formats. The selection in hex view is already there.

Discussion: I am not sure whether this is adequate here or should stay subject of a full blown hex editor.

**Comment by takeshixx** [comment]
I think it would be a nice enhancement for deen. I will look into it to see if it can be implemented without that much effort. While implementing the search function I've noticed that for larger buffers the performance is quite poor. I'm afraid that this will be the same for synchronization between plain and hex view.

**Comment by takeshixx** [comment]
First code is implemented in 54fb5fc8e9bf11b8fa83b10b019e0e9c387e1b73 as part of the current v2.0.0b5 release. It's still annoying when selecting multiple bytes with the mouse because of the way selection works in Qt tables. I have not yet figured out how to fix that.
